### ISSUE TITLE
When will the dataset be published?

### ISSUE THREAD

**Issue by swords123** [Junggy/HouseCat6D#1]
Hello, I am very interested in your work. When will this dataset be released?

**Comment by skarapanahalli** [comment]
Hi, is the dataset published yet ?
The dataset looks very intersting, I am waiting to use it to try my model.
Thanks!

**Comment by Junggy** [comment]
Hi! Thanks for your interest!

We are finalizing some formats for the dataset now and probably around july we will be able to release it!

**Comment by aaronchongth** [comment]
Hello there @Junggy! Apologies if I missed it during my search, has the dataset been published somewhere?

**Comment by ymxlzgy** [comment]
@aaronchongth @swords123 @skarapanahalli Hi guys, the dataset now is released. We are still uploading the related tools, but you can download it first and have a look here: https://sites.google.com/view/housecat6d/dataset?authuser=0
