### ISSUE TITLE
 Training and evaluation scripts

### ISSUE THREAD

**Issue by sseunghyuns** [Junggy/HouseCat6D#2]
Thank you for the great research. 

I want to train and evaluate my model on HouseCat6D. 
Still, is the training and evaluation code for VI-Net baseline available on [GitHub](https://github.com/Junggy/HouseCat6D/tree/main/VI-Net) the code reflected on the leaderboard?

**Comment by ymxlzgy** [comment]
> Thank you for the great research.
> 
> I want to train and evaluate my model on HouseCat6D. Still, is the training and evaluation code for VI-Net baseline available on [GitHub](https://github.com/Junggy/HouseCat6D/tree/main/VI-Net) the code reflected on the leaderboard?

Please check the folder VI-Net in this repo. If you have further questions, feel free to comment.

**Comment by sseunghyuns** [comment]
Thanks!
