### ISSUE TITLE
Any Trained Model?

### ISSUE THREAD

**Issue by diligent1787** [Junggy/HouseCat6D#5]
Hi, thanks for the wonderful work! Do you plan to release any model trained on HouseCat6D as well?

**Comment by ymxlzgy** [comment]
Hi. What exact model do you want to have?

**Comment by diligent1787** [comment]
> Hi. What exact model do you want to have?

Hi, thanks a lot for your response! Would you like to share a VI-Net model trained on HouseCat6D, since VI-Net is the latest method reported in your paper? It would be of great help to my research. Thanks again!

**Comment by ymxlzgy** [comment]
Please download them [here](http://www.campar.in.tum.de/public_datasets/2023_housecat6d_new/VI-Net_weights.zip). You need to modify the config file for correctly loading the models.

**Comment by diligent1787** [comment]
> Please download them [here](http://www.campar.in.tum.de/public_datasets/2023_housecat6d_new/VI-Net_weights.zip). You need to modify the config file for correctly loading the models.

Thanks so much! But it seems my connection requests kept repeating and I could not access the link, any idea? Could it be because I'm outside of Germany?

**Comment by zpyzpyzpyzpy** [comment]
Hi, may I ask if those trained models are trained with RGB-D or with RGB+P-D?
