### ISSUE TITLE
Camera Poses in Dataset

### ISSUE THREAD

**Issue by SimonSchwaiger** [Junggy/HouseCat6D#9]
Hello,

first of all thank you for the dataset and shared source code!

I am working on a data parser to reconstruct the scenes in Nerfstudio. However, I have trouble correctly converting the camera poses into the conventions used by Nerfstudio. Therefore, the following questions arose for me:

- Which conventions do the poses in scenexx/camera_pose follow? Is the camera coordinate system shown in [this video (link)](https://youtu.be/hHPlnsyfUGo?si=xM0tH--2PD1Rw-5S&t=204) at timestamp 3:24 accurate, i.e., x points right on the image plane, y points down on the image plane and z points towards the viewing direction?
- Are the provided transforms world to camera or camera to world? I assume world to camera, but it would be nice if it could be confirmed.

I am sorry if the information can be found in your documentation, I have read the paper and information on the paper's website, but I might have missed these details.

Thank you in advance!

**Comment by Junggy** [comment]
Hi! 

thanks for your interest in our dataset!

here are my answer: 

1. camera pose's orientation should follow typical camera model's orientation (e.g. x:right, y:down, z:forward) so, what you wrote is correct.

2. camera pose is "camera to world" meaning translation part of the camera pose should be the camera center in the world coordinate system. Note that colmap's camera format is "world to camera".

If NeRF studio offers colmap format, you can easily convert to colmap format by inverting the camera pose and convert the rotation matrix to quaternion. At the end our dataset's pose is obtained after colmap based refinement. But make sure to invert the camera pose.

If you have further question, please let me know!

**Comment by SimonSchwaiger** [comment]
Hi,

thank you for the quick reply! My issue was the assumption that the poses were "world to camera". I have adapted the code and now it works flawlessly. Thanks again for the help!
